import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]
OLD_DIGEST = "sha256:" + "a" * 64
NEW_DIGEST = "sha256:" + "b" * 64
SOURCE = "registry.example:5000/team/base:1.2.3"
PINNED = "registry.example:5000/team/base@" + OLD_DIGEST
HEADER = (
    "# Generated by scripts/lock-images.sh; do not edit by hand.\n"
    "# Review and commit source-tag changes in deploy/images.sources.\n"
)


class LockImagesTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        self.bin = self.root / "bin"
        self.bin.mkdir()
        # Isolate resolver selection from whatever is installed on the host.
        for command in ("dirname", "rm", "sed", "chmod", "mv", "cmp"):
            (self.bin / command).symlink_to(shutil.which(command))
        self.sources = self.root / "images.sources"
        self.sources.write_text(f"BASE_IMAGE|{SOURCE}\n")
        self.lock = self.root / "images.lock.env"
        self.original = HEADER + f"BASE_IMAGE={SOURCE}@{OLD_DIGEST}\n"
        self.lock.write_text(self.original)
        self.log = self.root / "registry.jsonl"
        self.registry_file = self.root / "registry.json"
        # The version tag has moved, but the reviewed manifest still exists.
        self.registry = {SOURCE: NEW_DIGEST, PINNED: OLD_DIGEST}
        self.env = dict(
            os.environ,
            PATH=str(self.bin),
            LOCK_TEST_LOG=str(self.log),
            LOCK_TEST_REGISTRY=str(self.registry_file),
        )

    def install_resolver(self, resolver):
        for command in ("skopeo", "crane", "docker"):
            (self.bin / command).unlink(missing_ok=True)
        command = "docker" if resolver == "buildx" else resolver
        executable = self.bin / command
        executable.write_text(
            f"#!{sys.executable}\n"
            """import json
import os
from pathlib import Path
import sys

command = Path(sys.argv[0]).name
args = sys.argv[1:]
if command == 'docker' and args == ['buildx', 'version']:
    sys.exit(0)
prefix = {
    'skopeo': ['inspect', '--format', '{{.Digest}}'],
    'crane': ['digest'],
    'docker': ['buildx', 'imagetools', 'inspect'],
}[command]
assert args[:-1] == prefix, args
ref = args[-1]
if command == 'skopeo':
    assert ref.startswith('docker://'), ref
    ref = ref[len('docker://'):]
    # containers/image rejects tag+digest, unlike Docker and crane.
    assert '@' not in ref or ':' not in ref.split('@')[0].rsplit('/', 1)[-1], ref
with open(os.environ['LOCK_TEST_LOG'], 'a') as stream:
    stream.write(json.dumps(ref) + '\\n')
registry = json.loads(Path(os.environ['LOCK_TEST_REGISTRY']).read_text())
value = registry.get(ref)
if value is None:
    sys.exit('manifest unavailable')
digest = value['digest'] if isinstance(value, dict) else value
if command == 'docker':
    print('Name: ' + ref)
    print('Digest: ' + digest)
    print('  Name: platform-specific child manifest')
    print('  Digest: sha256:' + 'c' * 64)
else:
    print(digest)
sys.exit(value.get('exit', 0) if isinstance(value, dict) else 0)
"""
        )
        executable.chmod(0o755)

    def run_lock(self, check=True):
        self.registry_file.write_text(json.dumps(self.registry))
        self.log.unlink(missing_ok=True)
        args = ["/bin/sh", str(ROOT / "scripts/lock-images.sh")]
        if check:
            args.append("--check")
        args.extend((str(self.sources), str(self.lock)))
        result = subprocess.run(
            args, env=self.env, capture_output=True, text=True, timeout=10
        )
        calls = (
            [json.loads(line) for line in self.log.read_text().splitlines()]
            if self.log.exists()
            else []
        )
        self.assertEqual(list(self.root.glob("images.lock.env.tmp.*")), [])
        return result, calls

    def test_check_keeps_reviewed_digest_when_tag_moves_for_every_resolver(self):
        for resolver in ("skopeo", "crane", "buildx"):
            with self.subTest(resolver=resolver):
                self.install_resolver(resolver)
                result, calls = self.run_lock()
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(calls, [PINNED])
                self.assertEqual(self.lock.read_text(), self.original)

    def test_explicit_update_resolves_tags_for_every_resolver(self):
        for resolver in ("skopeo", "crane", "buildx"):
            with self.subTest(resolver=resolver):
                self.install_resolver(resolver)
                result, calls = self.run_lock(check=False)
                self.assertEqual(result.returncode, 0, result.stderr)
                self.assertEqual(calls, [SOURCE])
                self.assertEqual(
                    self.lock.read_text(), self.original.replace(OLD_DIGEST, NEW_DIGEST)
                )

    def test_invalid_locks_fail_before_registry_access_without_rewriting(self):
        self.install_resolver("skopeo")
        invalid_locks = {
            "missing": HEADER,
            "duplicate": self.original + f"BASE_IMAGE={SOURCE}@{OLD_DIGEST}\n",
            "extra": self.original + f"EXTRA_IMAGE={SOURCE}@{OLD_DIGEST}\n",
            "changed_source": self.original.replace(":1.2.3@", ":1.2.4@"),
            "non_hex": self.original.replace(OLD_DIGEST, "sha256:" + "x" * 64),
            "short": self.original.replace(OLD_DIGEST, "sha256:" + "a" * 63),
            "long": self.original.replace(OLD_DIGEST, "sha256:" + "a" * 65),
            "algorithm": self.original.replace("sha256:", "sha512:"),
            "shell_code": self.original + f"touch {self.root / 'executed'}\n",
        }
        for name, contents in invalid_locks.items():
            with self.subTest(name=name):
                self.lock.write_text(contents)
                result, calls = self.run_lock()
                self.assertNotEqual(result.returncode, 0)
                self.assertEqual(calls, [])
                self.assertEqual(self.lock.read_text(), contents)
                self.assertFalse((self.root / "executed").exists())

    def test_duplicate_and_invalid_sources_fail_before_registry_access(self):
        self.install_resolver("skopeo")
        invalid_sources = (
            f"BASE_IMAGE|{SOURCE}\nBASE_IMAGE|{SOURCE}\n",
            f"1IMAGE|{SOURCE}\n",
            "BASE_IMAGE|registry.example:5000/team/base\n",
            f"BASE_IMAGE|{SOURCE}@{OLD_DIGEST}\n",
            f"BASE_IMAGE|{SOURCE}|extra\n",
        )
        for contents in invalid_sources:
            with self.subTest(contents=contents):
                self.sources.write_text(contents)
                result, calls = self.run_lock()
                self.assertNotEqual(result.returncode, 0)
                self.assertEqual(calls, [])
                self.assertEqual(self.lock.read_text(), self.original)

    def test_check_rejects_unavailable_or_different_registry_manifest(self):
        self.install_resolver("skopeo")
        for registry in ({}, {PINNED: NEW_DIGEST}):
            with self.subTest(registry=registry):
                self.registry = registry
                result, calls = self.run_lock()
                self.assertNotEqual(result.returncode, 0)
                self.assertEqual(calls, [PINNED])
                self.assertEqual(self.lock.read_text(), self.original)

    def test_failed_inspection_with_valid_output_is_not_accepted(self):
        for resolver in ("skopeo", "crane", "buildx"):
            for check in (False, True):
                with self.subTest(resolver=resolver, check=check):
                    self.install_resolver(resolver)
                    ref = PINNED if check else SOURCE
                    self.registry = {ref: {"digest": OLD_DIGEST, "exit": 1}}
                    result, calls = self.run_lock(check=check)
                    self.assertNotEqual(result.returncode, 0)
                    self.assertEqual(calls, [ref])
                    self.assertEqual(self.lock.read_text(), self.original)

    def test_update_rejects_invalid_registry_digest_and_preserves_lock(self):
        self.install_resolver("skopeo")
        self.registry = {SOURCE: "sha256:" + "z" * 64}
        result, calls = self.run_lock(check=False)
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(calls, [SOURCE])
        self.assertEqual(self.lock.read_text(), self.original)

    def test_missing_lock_cannot_be_created_in_check_mode(self):
        self.install_resolver("skopeo")
        self.lock.unlink()
        result, calls = self.run_lock()
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(calls, [])
        self.assertFalse(self.lock.exists())

    def test_check_verifies_all_entries(self):
        self.install_resolver("skopeo")
        second_source = "registry.example/team/other:4.5.6"
        second_pinned = "registry.example/team/other@" + NEW_DIGEST
        self.sources.write_text(f"BASE_IMAGE|{SOURCE}\nOTHER_IMAGE|{second_source}\n")
        self.lock.write_text(
            self.original + f"OTHER_IMAGE={second_source}@{NEW_DIGEST}\n"
        )
        self.registry[second_pinned] = NEW_DIGEST
        result, calls = self.run_lock()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(calls, [PINNED, second_pinned])


if __name__ == "__main__":
    unittest.main()
