#!/bin/sh
set -eu
umask 077

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
sources=${1:-"$root/deploy/images.sources"}
output=${2:-"$root/deploy/images.lock.env"}
tmp=${output}.tmp.$$
trap 'rm -f "$tmp"' EXIT HUP INT TERM

if command -v skopeo >/dev/null 2>&1; then
    resolver=skopeo
elif command -v crane >/dev/null 2>&1; then
    resolver=crane
elif docker buildx version >/dev/null 2>&1; then
    resolver=buildx
else
    printf '%s\n' 'lock-images: install skopeo/crane or enable docker buildx' >&2
    exit 1
fi

resolve_digest() {
    ref=$1
    case "$resolver" in
        skopeo) skopeo inspect --format '{{.Digest}}' "docker://$ref" ;;
        crane) crane digest "$ref" ;;
        buildx)
            docker buildx imagetools inspect "$ref" | \
                sed -n 's/^Digest:[[:space:]]*//p' | sed -n '1p'
            ;;
    esac
}

{
    printf '%s\n' '# Generated by scripts/lock-images.sh; do not edit by hand.'
    printf '%s\n' '# Review and commit source-tag changes in deploy/images.sources.'
} > "$tmp"

while IFS='|' read -r name ref; do
    case "$name" in
        ''|'#'*) continue ;;
    esac
    case "$name" in
        *[!A-Z0-9_]*)
            printf '%s\n' "lock-images: invalid variable name in $sources" >&2
            exit 1
            ;;
    esac
    test -n "$ref" || {
        printf '%s\n' "lock-images: missing image reference for $name" >&2
        exit 1
    }

    digest=$(resolve_digest "$ref")
    case "$digest" in
        sha256:????????????????????????????????????????????????????????????????) ;;
        *)
            printf '%s\n' "lock-images: registry returned an invalid digest for $ref" >&2
            exit 1
            ;;
    esac
    printf '%s=%s@%s\n' "$name" "$ref" "$digest" >> "$tmp"
    printf '%s\n' "locked $name ($ref)" >&2
done < "$sources"

chmod 0644 "$tmp"
mv -f "$tmp" "$output"
trap - EXIT HUP INT TERM
printf '%s\n' "wrote $output"
